name: CI - Test on Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build and Test
      run: |
        xcodebuild clean build \
          -scheme CursorFinder \
          -configuration Debug \
          -destination 'platform=macOS' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
    
    - name: Verify Universal Binary
      run: |
        xcodebuild -scheme CursorFinder \
          -configuration Release \
          -derivedDataPath ./build \
          -destination 'generic/platform=macOS' \
          -archivePath ./build/CursorFinder.xcarchive \
          archive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
        
        # Check architectures
        file build/CursorFinder.xcarchive/Products/Applications/CursorFinder.app/Contents/MacOS/CursorFinder | grep "universal"