name: Release Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Import Certificate
        env:
          CERT_BASE64: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
          CERT_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        run: |
          if [ -z "$CERT_BASE64" ]; then
            echo "No certificate provided, skipping import"
            exit 0
          fi

          KEYCHAIN_PATH=$RUNNER_TEMP/build.keychain-db
          KEYCHAIN_PASSWORD=$(openssl rand -base64 32)

          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

          echo "$CERT_BASE64" | base64 -d -o certificate.p12
          security import certificate.p12 -P "$CERT_PASSWORD" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"
          security list-keychain -d user -s "$KEYCHAIN_PATH"

          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

      - name: Build Universal Binary
        env:
          TEAM_ID: ${{ secrets.APPLE_DEVELOPMENT_TEAM }}
          SIGN_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
        run: |
          if [ -n "$SIGN_IDENTITY" ]; then
            echo "Building with signing"
            xcodebuild -scheme CursorFinder \
              -configuration Release \
              -derivedDataPath ./build \
              -destination 'generic/platform=macOS' \
              -archivePath ./build/CursorFinder.xcarchive \
              archive \
              CODE_SIGN_IDENTITY="$SIGN_IDENTITY" \
              DEVELOPMENT_TEAM="$TEAM_ID" \
              CODE_SIGNING_REQUIRED=YES
          else
            echo "Building without signing"
            xcodebuild -scheme CursorFinder \
              -configuration Release \
              -derivedDataPath ./build \
              -destination 'generic/platform=macOS' \
              -archivePath ./build/CursorFinder.xcarchive \
              archive \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO
          fi

      - name: Create ZIP
        run: |
          cd build/CursorFinder.xcarchive/Products/Applications
          zip -r ../../../CursorFinder.zip CursorFinder.app
          cd -
          mv build/CursorFinder.zip .

      - name: Calculate SHA256
        id: sha256
        run: |
          SHA256=$(shasum -a 256 CursorFinder.zip | cut -d' ' -f1)
          echo "sha256=${SHA256}" >> "$GITHUB_OUTPUT"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: CursorFinder.zip

      - name: Update Homebrew Formula
        run: |
          VERSION="${{ github.event.release.tag_name }}"

          sed -i '' "s|url \".*\"|url \"https://github.com/kawaz/CursorFinder/releases/download/${VERSION}/CursorFinder.zip\"|" Formula/cursorfinder.rb
          sed -i '' "s|sha256 \".*\"|sha256 \"${{ steps.sha256.outputs.sha256 }}\"|" Formula/cursorfinder.rb

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/cursorfinder.rb
          git commit -m "Update formula for version ${VERSION} [skip ci]"
          git push origin HEAD:main
