name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Build Universal Binary
        run: |
          xcodebuild -scheme CursorFinder \
            -configuration Release \
            -derivedDataPath ./build \
            -destination 'generic/platform=macOS' \
            -archivePath ./build/CursorFinder.xcarchive \
            archive
      
      - name: Create ZIP
        run: |
          cd build/CursorFinder.xcarchive/Products/Applications
          zip -r ../../../CursorFinder.zip CursorFinder.app
          cd -
          mv build/CursorFinder.zip .
      
      - name: Calculate SHA256
        id: sha256
        run: |
          SHA256=$(shasum -a 256 CursorFinder.zip | cut -d' ' -f1)
          echo "sha256=${SHA256}" >> $GITHUB_OUTPUT
      
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: CursorFinder.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update Homebrew Formula
        run: |
          # Get version from release tag
          VERSION="${{ github.event.release.tag_name }}"
          
          # Update formula with new URL and SHA256
          sed -i '' "s|url \".*\"|url \"https://github.com/kawaz/CursorFinder/releases/download/${VERSION}/CursorFinder.zip\"|" Formula/cursorfinder.rb
          sed -i '' "s|sha256 \".*\"|sha256 \"${{ steps.sha256.outputs.sha256 }}\"|" Formula/cursorfinder.rb
          
          # Commit and push
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/cursorfinder.rb
          git commit -m "Update formula for version ${VERSION} [skip ci]"
          git push origin HEAD:main