name: Simple Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build Universal Binary
        run: |
          xcodebuild -scheme CursorFinder \
            -configuration Release \
            -derivedDataPath ./build \
            -destination 'generic/platform=macOS' \
            -archivePath ./build/CursorFinder.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

      - name: Create ZIP
        run: |
          cd build/CursorFinder.xcarchive/Products/Applications
          zip -r ../../../CursorFinder.zip CursorFinder.app
          cd -
          mv build/CursorFinder.zip .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: CursorFinder.zip

      - name: Update Formula
        run: |
          # バージョンとSHA256を取得
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"  # v接頭辞を削除
          SHA256=$(shasum -a 256 CursorFinder.zip | awk '{print $1}')
          
          # Formulaを更新
          sed -i '' \
            -e "s|download/v[0-9.]*|download/v${VERSION}|" \
            -e "s|sha256 \"[a-f0-9]*\"|sha256 \"${SHA256}\"|" \
            Formula/cursorfinder.rb
          
          # 変更をコミット&プッシュ
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/cursorfinder.rb
          git commit -m "Update Formula to v${VERSION}"
          git push