name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update Formula
        run: |
          # Download the release asset to calculate SHA256
          curl -L -o CursorFinder.zip "${{ github.event.release.assets[0].browser_download_url }}"
          SHA256=$(shasum -a 256 CursorFinder.zip | cut -d' ' -f1)
          
          # Update the formula
          sed -i "s|url \".*\"|url \"${{ github.event.release.assets[0].browser_download_url }}\"|" Formula/cursorfinder.rb
          sed -i "s|sha256 \".*\"|sha256 \"${SHA256}\"|" Formula/cursorfinder.rb
          
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/cursorfinder.rb
          git commit -m "Update formula for version ${{ github.event.release.tag_name }}"
          git push